tool = filter2

all:
	./$(tool) $(file)
	cp ./test1.txt ../../src/test/scala/gcd/fivestage_difftest/obj_dir/test1.txt
	cp ./test1.txt ../../src/test/scala/gcd/utest/obj_dir/test1.txt
	cp ./test1.txt ../../src/test/scala/gcd/toptest/obj_dir/test1.txt